name 'github_backup_utils'
maintainer 'Perficient DevOps'
maintainer_email 'devops@perficient.com'
license 'All Rights Reserved'
description 'Installs/Configures github_backup_utils'
long_description 'Installs/Configures github_backup_utils'
version '0.1.0'
chef_version '>= 14.0'

issues_url 'https://github.com/Perficient-DevOps/github_backup_utils/issues'
source_url 'https://github.com/Perficient-DevOps/github_backup_utils'

supports 'rhel'
supports 'centos'
supports 'amazon'
